[package]
name = "reco"
version = "0.0.0"
edition = "2024"
description = "An ECO (Encyclopaedia of Chess Openings) crate"
categories = ["data-structures", "game-development", "no-std", "api-bindings"]
keywords = ["chess", "eco", "dataset", "lichess"]
repository = "https://github.com/tigerros/reco"
license = "GPL-3"
rust-version = "1.85.1" # remember to update check.yml
readme = "README.md"
include = ["src", "README.md", "LICENSE"]

[dependencies]
deranged = { version = "0.4.0", default-features = false }
serde = { version = "1.0.126", default-features = false, features = ["derive"], optional = true }
shakmaty = { git = "https://github.com/niklasf/shakmaty", default-features = false }

[features]
serde = ["dep:serde", "deranged/serde"]
book = []
