[package]
name = "reco"
version = "0.0.0"
edition = "2024"
description = "An ECO (Encyclopaedia of Chess Openings) crate"
categories = ["data-structures", "game-development", "no-std", "no-std::no-alloc", "api-bindings"]
keywords = ["chess", "eco", "dataset", "lichess"]
repository = "https://github.com/tigerros/reco"
license = "GPL-3"
rust-version = "1.85.1"

[dependencies]
constcat = { version = "0.6.0", optional = true }
deranged = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
shakmaty = { workspace = true }

[features]
serde = ["dep:serde", "deranged/serde"]
alloc = ["serde?/alloc"]
openings = []
openings-concat = ["openings", "constcat"]

[workspace]
resolver = "3"
members = ["updater"]

[workspace.dependencies]
shakmaty = { git = "https://github.com/tigerros/shakmaty", branch = "dev2", default-features = false }
deranged = { version = "0.4.0", default-features = false }
serde = { version = "1", default-features = false }
