[workspace]
resolver = "3"
members = ["crates/book", "crates/core", "crates/librarian", "crates/reco"]

[workspace.dependencies]
shakmaty = { git = "https://github.com/tigerros/shakmaty", branch = "dev2", default-features = false }
deranged = { version = "~0.4", default-features = false }
reco-book = { version = "0.1.0", path = "crates/book" }
reco-core = { version = "0.0.0", path = "crates/core" }
