[package]
name = "find-opening"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
reco = { workspace = true, features = ["book", "alloc"] }
ureq = "3.0.11"
rpgn = "0.8.1"
pgn-reader = "0.26.0"
http = "1.3.1"
shakmaty = { workspace = true }