[package]
name = "find-opening"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
http = "1.3.1"
pgn-reader = "0.27.0"
reco = { workspace = true, features = ["book", "alloc"] }
shakmaty = { workspace = true }
ureq = "3.0.11"
