name: Bump book

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run librarian
        env:
          GITHUB_TOKEN: ${{ secrets.GET_GITHUB_PAT }}
        run: |
          echo "LIBRARIAN=$(cargo run -p librarian --quiet)" >> $GITHUB_ENV

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Check for changes
        if: env.LIBRARIAN == 'success'
        run: |
          git config --global user.name "librarian"
          git config --global user.email "github-actions@users.noreply.github.com"
          echo "CHANGED=false" >> $GITHUB_ENV
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Bump patch version if changes
        if: env.CHANGED == 'true' && env.LIBRARIAN == 'success'
        run: |
          file=Cargo.toml
          version_line=$(grep "^version" "$file")
          version=$(echo $version_line | cut -d '"' -f2)
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          sed -i "s/^version = \".*\"/version = \"$new_version\"/" "$file"

      - name: Read commit source SHA
        if: env.CHANGED == 'true' && env.LIBRARIAN == 'success'
        run: |
          echo "SHA=$(cat commit-source.txt)" >> $GITHUB_ENV
          echo "SHORT_SHA=$(cut -c1-7 < commit-source.txt)" >> $GITHUB_ENV

      - name: Create pull request
        if: env.CHANGED == 'true' && env.LIBRARIAN == 'success'
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Bump book using `${{ env.SHORT_SHA }}`'
          delete-branch: 'true'
          commit-message: 'bump book'
          branch: 'bump-book-${{ env.SHORT_SHA }}'
          body: '
            Running `librarian` resulted in a diff, which is why this PR was made.
            Apart from using `librarian`''s output, this PR also bumps the patch version of `reco`.
            However, if the Check SemVer workflow fails, the minor version will need to be bumped instead.
            Furthermore, the crate must be published manually.
            
            This PR was made using this commit: [lichess-org/chess-openings/${{ env.SHORT_SHA }}](https://github.com/lichess-org/chess-openings/commit/${{ env.SHA }}).
            **However, this commit might not be new.** It is possible that only `librarian` and the output changed.
            If `commit-source.txt` changed, it is likely that the diff is caused by that new commit.'
          author: 'librarian <github-actions@users.noreply.github.com>'
          committer: 'librarian <github-actions@users.noreply.github.com>'
          sign-commits: 'true'