name: Check
on: [push, pull_request]

jobs:
  check-others:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Check except reco lib
        run: cargo check --workspace --bins --examples --tests --benches

  check-reco:
    strategy:
      matrix:
        toolchain:
          - "stable"
          - "nightly"
        include:
          - toolchain: "nightly"
            flags: "-Z direct-minimal-versions"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: x86_64-unknown-none

      - name: No-std
        run: rustup run ${{ matrix.toolchain }} cargo hack check --feature-powerset --skip proptest,arbitrary,std,default --target x86_64-unknown-none ${{ matrix.flags }}

      - name: Std
        run: rustup run ${{ matrix.toolchain }} cargo hack check --feature-powerset ${{ matrix.flags }}