name: Check
on: [push, pull_request]

jobs:
  check-librarian:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Check
        run: cargo check --manifest-path librarian/Cargo.toml --all-targets -Z direct-minimal-versions

  check-reco:
    strategy:
      matrix:
        toolchain:
          - "1.85.1" # remember to update rust-version in Cargo.toml
          - "stable"
          - "nightly"
        include:
          - toolchain: "nightly"
            flags: "-Z direct-minimal-versions"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: x86_64-unknown-none

      - name: Check
        run: rustup run ${{ matrix.toolchain }} cargo hack check --feature-powerset --target x86_64-unknown-none ${{ matrix.flags }}