name: Check SemVer
on: [push, pull_request]

jobs:
  check-semver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Check SemVer
        run: cargo hack --feature-powerset semver-checks --workspace