name: Doc check
on: [push, pull_request]

jobs:
  doc-check:
    strategy:
      matrix:
        manifest:
          - "Cargo.toml"
          - "librarian/Cargo.toml"

    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack

      - name: Doc check
        run: cargo hack --feature-powerset doc --manifest-path ${{ matrix.manifest }}