name: Format
on: [push, pull_request]

jobs:
  format:
    strategy:
      matrix:
        manifest:
          - "Cargo.toml"
          - "librarian/Cargo.toml"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Format
        run: cargo +nightly fmt --manifest-path ${{ matrix.manifest }} --check