name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        manifest:
          - "Cargo.toml"
          - "librarian/Cargo.toml"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: Test
        run: cargo hack test --feature-powerset --manifest-path ${{ matrix.manifest }} --all-targets -q